### ISSUE TITLE
How to crop the input image to get the same result as that in your paper?

### ISSUE THREAD

**Issue by xuxy09** [tpfister/caffe-heatmap#2]
Hi, the test input images you provide are slightly different with the origin images in Pose-in-the-Wild dataset. Could you tell me how you did cropping? I can't find related information in your paper. Thanks！

**Comment by tpfister** [comment]
Hi, 

The labels and pre-cropped images for training and testing are now available.

http://tomas.pfister.fi/flic_train_cropped_multfact282.tgz
http://tomas.pfister.fi/flic_test_cropped_multfact282.tgz

**Comment by samouha** [comment]
@tpfister  can you tell us please, how did you do the cropping of images for both test and train? 
I need to know that because I will test your model on my own dataset.

**Comment by mindcont** [comment]
Hi, @xuxy09 @samouha 
I am equally puzzled, have you been solved this?
