### ISSUE TITLE
Optic flow computation

### ISSUE THREAD

**Issue by murthypramod** [tpfister/caffe-heatmap#6]
Hi Tomas, 

I couldn't find the part of the optic flow calculation and the temporal pooling layer. Could you guide how did calculate it during the training ?

**Comment by tpfister** [comment]
Hi Pramod,

We precomputed optical flow for the datasets using fastdeepflow and wrote a caffe data layer to do the heatmap warping.  Unfortunately that data layer needs significant cleanup before release so we won't be able to release it anytime soon.
