### ISSUE TITLE
My computer shut down when I try to compile the caffe-heatmap code, why?

### ISSUE THREAD

**Issue by samouha** [tpfister/caffe-heatmap#7]
When I try to compile the caffe-heatmap code with : "sh train_heatmap.sh heatmap-flic-fusion 0"(my gpu_id is 0), the process of training begin, but after about 20 minutes, it's still stacked at "#Iteration0"  and then the computer shut down !!!
I can't know what is happening exactly and how to solve it !!
Can any one help me please.
Thanks a lot :)

**Comment by samouha** [comment]
@fengyang0317 can you help me to solve this problem please ? :) 
I am using: Ubuntu 14.04 LTS-64 bits, and my GPU is GeForce 630 (4GB)
I am stuckued here for many weeks :(

**Comment by tpfister** [comment]
Does training with standard Caffe work for you?

**Comment by samouha** [comment]
yes . it works fine with standard Caffe but with this code it does"nt :(

**Comment by samouha** [comment]
Can I train this code on CPU mode ? if yes, please tell me how can I do it , because it seems that the problem here is a question of memory (I guess)

**Comment by tpfister** [comment]
You could try decrease batchsize if you're running out of memory

CPU mode should work just like in standard caffe

**Comment by samouha** [comment]
It works fine for me right now. Actually, I changed the batchsize in train phase (from 14 to 1)and the number of iter_max (from 10000000 to 30000). I also, changed my GPU card (from GTX 630 to GTX 960 which works fine with all caffe codes ans test ).
Thanks for your collaboration :)
